%{
  "eastus" => %{"description" => "(US) East US"},
  "eastus2" => %{"description" => "(US) East US 2"},
  "southcentralus" => %{"description" => "(US) South Central US"},
  "westus2" => %{"description" => "(US) West US 2"},
  "westus3" => %{"description" => "(US) West US 3"},
  "australiaeast" => %{"description" => "(Asia Pacific) Australia East"},
  "southeastasia" => %{"description" => "(Asia Pacific) Southeast Asia"},
  "northeurope" => %{"description" => "(Europe) North Europe"},
  "swedencentral" => %{"description" => "(Europe) Sweden Central"},
  "uksouth" => %{"description" => "(Europe) UK South"},
  "westeurope" => %{"description" => "(Europe) West Europe"},
  "centralus" => %{"description" => "(US) Central US"},
  "southafricanorth" => %{"description" => "(Africa) South Africa North"},
  "centralindia" => %{"description" => "(Asia Pacific) Central India"},
  "eastasia" => %{"description" => "(Asia Pacific) East Asia"},
  "japaneast" => %{"description" => "(Asia Pacific) Japan East"},
  "koreacentral" => %{"description" => "(Asia Pacific) Korea Central"},
  "canadacentral" => %{"description" => "(Canada) Canada Central"},
  "francecentral" => %{"description" => "(Europe) France Central"},
  "germanywestcentral" => %{"description" => "(Europe) Germany West Central"},
  "italynorth" => %{"description" => "(Europe) Italy North"},
  "norwayeast" => %{"description" => "(Europe) Norway East"},
  "polandcentral" => %{"description" => "(Europe) Poland Central"},
  "switzerlandnorth" => %{"description" => "(Europe) Switzerland North"},
  "mexicocentral" => %{"description" => "(Mexico) Mexico Central"},
  "uaenorth" => %{"description" => "(Middle East) UAE North"},
  "brazilsouth" => %{"description" => "(South America) Brazil South"},
  "israelcentral" => %{"description" => "(Middle East) Israel Central"},
  "qatarcentral" => %{"description" => "(Middle East) Qatar Central"},
  "centralusstage" => %{"description" => "(US) Central US (Stage)"},
  "eastusstage" => %{"description" => "(US) East US (Stage)"},
  "eastus2stage" => %{"description" => "(US) East US 2 (Stage)"},
  "northcentralusstage" => %{"description" => "(US) North Central US (Stage)"},
  "southcentralusstage" => %{"description" => "(US) South Central US (Stage)"},
  "westusstage" => %{"description" => "(US) West US (Stage)"},
  "westus2stage" => %{"description" => "(US) West US 2 (Stage)"},
  "eastasiastage" => %{"description" => "(Asia Pacific) East Asia (Stage)"},
  "southeastasiastage" => %{"description" => "(Asia Pacific) Southeast Asia (Stage)"},
  "brazilus" => %{"description" => "(South America) Brazil US"},
  "eastusstg" => %{"description" => "(US) East US STG"},
  "northcentralus" => %{"description" => "(US) North Central US"},
  "westus" => %{"description" => "(US) West US"},
  "japanwest" => %{"description" => "(Asia Pacific) Japan West"},
  "jioindiawest" => %{"description" => "(Asia Pacific) Jio India West"},
  "centraluseuap" => %{"description" => "(US) Central US EUAP"},
  "eastus2euap" => %{"description" => "(US) East US 2 EUAP"},
  "westcentralus" => %{"description" => "(US) West Central US"},
  "southafricawest" => %{"description" => "(Africa) South Africa West"},
  "australiacentral" => %{"description" => "(Asia Pacific) Australia Central"},
  "australiacentral2" => %{"description" => "(Asia Pacific) Australia Central 2"},
  "australiasoutheast" => %{"description" => "(Asia Pacific) Australia Southeast"},
  "jioindiacentral" => %{"description" => "(Asia Pacific) Jio India Central"},
  "koreasouth" => %{"description" => "(Asia Pacific) Korea South"},
  "southindia" => %{"description" => "(Asia Pacific) South India"},
  "westindia" => %{"description" => "(Asia Pacific) West India"},
  "canadaeast" => %{"description" => "(Canada) Canada East"},
  "francesouth" => %{"description" => "(Europe) France South"},
  "germanynorth" => %{"description" => "(Europe) Germany North"},
  "norwaywest" => %{"description" => "(Europe) Norway West"},
  "switzerlandwest" => %{"description" => "(Europe) Switzerland West"},
  "ukwest" => %{"description" => "(Europe) UK West"},
  "uaecentral" => %{"description" => "(Middle East) UAE Central"},
  "brazilsoutheast" => %{"description" => "(South America) Brazil Southeast"}
}
